In [1]:
import numpy as np
import pandas as pd

In [2]:
!pip install gensim
!pip install nltk

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 52.2 MB/s eta 0:00:00


In [12]:
df = pd.read_csv("final.csv", index_col=0)

In [13]:
df

,sentiment,clean_text
0,positive,one reviewers mention watch oz episode youll ...
1,positive,wonderful little production film technique una...
2,positive,think wonderful way spend tears eye hot summer...
3,negative,basically theres family little boy jake think ...
4,positive,petter matteis love tears eye money visually s...
...,...,...
49995,positive,think movie right good job wasnt creative orig...
49996,negative,bad plot bad dialogue bad act idiotic direct a...
49997,negative,catholic teach parochial elementary school nun...
49998,negative,im go disagree previous comment side maltin on...


In [14]:
import nltk
nltk.download('punkt_tab')
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

story = []
for review in df["clean_text"]:
  raw_sent = sent_tokenize(review)
  for w in raw_sent:
    story.append(simple_preprocess(w))



[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [15]:
story

[['one',
  'reviewers',
  'mention',
  'watch',
  'oz',
  'episode',
  'youll',
  'hook',
  'right',
  'exactly',
  'happen',
  'methe',
  'first',
  'thing',
  'strike',
  'oz',
  'brutality',
  'unflinching',
  'scenes',
  'violence',
  'set',
  'right',
  'word',
  'go',
  'trust',
  'show',
  'faint',
  'hearted',
  'timid',
  'show',
  'pull',
  'punch',
  'regard',
  'drug',
  'sex',
  'violence',
  'hardcore',
  'classic',
  'use',
  'wordit',
  'call',
  'oz',
  'nickname',
  'give',
  'oswald',
  'maximum',
  'security',
  'state',
  'penitentary',
  'focus',
  'mainly',
  'emerald',
  'city',
  'experimental',
  'section',
  'prison',
  'cells',
  'glass',
  'front',
  'face',
  'inwards',
  'privacy',
  'high',
  'agenda',
  'em',
  'city',
  'home',
  'manyaryans',
  'muslims',
  'gangstas',
  'latinos',
  'christians',
  'italians',
  'irish',
  'moreso',
  'scuffle',
  'death',
  'star',
  'dodgy',
  'dealings',
  'shady',
  'agreements',
  'never',
  'far',
  'awayi',
  

In [16]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

Y = encoder.fit_transform(df['sentiment'])
X = df['clean_text']

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_val, Y_train, Y_val = train_test_split(X, Y, test_size=0.2, random_state=1)

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(
    max_features=10000,
    min_df=5,
    max_df=0.8
)
tf_train = tf.fit_transform(X_train)
tf_val = tf.transform(X_val)

In [46]:
tf_train[1].shape

(1, 10000)

In [47]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix,precision_score


rf = RandomForestClassifier()
rf.fit(tf_train, Y_train)
y_pred = rf.predict(tf_val)
print(accuracy_score(Y_val, y_pred))
print(confusion_matrix(Y_val, y_pred))
print(precision_score(Y_val, y_pred))

0.8419725695845098
[[4174  737]
 [ 830 4175]]
0.8499592833876222


In [57]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression()

LR.fit(tf_train, Y_train)

y_pred = LR.predict(tf_val)
print(accuracy_score(Y_val, y_pred))
print(confusion_matrix(Y_val, y_pred))
print(precision_score(Y_val, y_pred))

0.8881605486083098
[[4315  596]
 [ 513 4492]]
0.8828616352201258


In [59]:
from sklearn.naive_bayes import MultinomialNB

MNB = MultinomialNB()

MNB.fit(tf_train, Y_train)
y_pred = MNB.predict(tf_val)

print(accuracy_score(Y_val, y_pred))
print(confusion_matrix(Y_val, y_pred))
print(precision_score(Y_val, y_pred))

0.8521581282775312
[[4176  735]
 [ 731 4274]]
0.8532641245757636


In [50]:
import sklearn
print(sklearn.__version__)

1.6.1


In [51]:
import sys
print(sys.version)

3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]


In [30]:
!pip freeze > requirements.txt

In [53]:
import sklearn, pandas, numpy, nltk, gensim

print("sklearn:", sklearn.__version__)
print("pandas:", pandas.__version__)
print("numpy:", numpy.__version__)
print("nltk:", nltk.__version__)
print("gensim:", gensim.__version__)

sklearn: 1.6.1
pandas: 2.2.2
numpy: 2.0.2
nltk: 3.9.1
gensim: 4.4.0


In [55]:
print(encoder.classes_)

['negative' 'positive']


In [56]:
import pickle

In [60]:
pickle.dump(tf,open('vectorizer.pkl','wb'))
pickle.dump(LR,open('model.pkl','wb'))

In [61]:

pickle.dump(encoder,open("label_encoder.pkl", "wb"))